//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordisCompany.Models
{
    using System;
    using System.Collections.Generic;

    //The rentItems model is designed for Cordis Company rental items such as pumps that have a unique ID and name, measurements, images, styles, and estimated delivery.
    public partial class rentItem
    {
        public int ID { get; set; }
        public string itemName { get; set; }
        public Nullable<int> reach1 { get; set; }
        public Nullable<int> reach2 { get; set; }
        public string imgString { get; set; }
        public string style { get; set; }
        public Nullable<int> progress { get; set; }
    }
}
